dist: trusty

sudo: required

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - gcc-5
      - g++-5

before_install:
  - sudo apt-get purge openjdk-9*
  - sudo apt-get purge oracle-java9*
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.28.1/bazel_0.28.1-linux-x86_64.deb'
  - chmod +x bazel_0.28.1-linux-x86_64.deb
  - sudo dpkg -i bazel_0.28.1-linux-x86_64.deb

script:
  - ./src/tools/check-buildifier.sh
  - bazel test //src/...

